### ISSUE TITLE
Curso GraphQL 

### ISSUE THREAD

**Issue by DevJoseWeb** [m4rciosouza/kazapp#1]
Professor Màrcio, fiquei sabendo que o senhor trabalha freneticamente sem sair de casa a 3 meses em um super projeto de GraphQL com Spring Boot MongoDB Redis Posgres e no Front React ! e Macine Learning e Data Science em Python. Usando Java 11 com LAMBDAS selvagemente procede....

Quando inicia ?

Esperando atentamente !

Jr

**Comment by m4rciosouza** [comment]
Olá,

não procede, a sugestão é bastante interessante, na verdade para mais de um curso pois se tratam de assuntos um pouco distintos, mas não tenho previsão para iniciar a criação desses cursos.

Márcio.
